/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Hp5FaqAccordion {
    }
    interface Hp5FaqAccordionContainer {
    }
    interface MyComponentA {
    }
    interface MyComponentB {
    }
}
declare global {
    interface HTMLHp5FaqAccordionElement extends Components.Hp5FaqAccordion, HTMLStencilElement {
    }
    var HTMLHp5FaqAccordionElement: {
        prototype: HTMLHp5FaqAccordionElement;
        new (): HTMLHp5FaqAccordionElement;
    };
    interface HTMLHp5FaqAccordionContainerElement extends Components.Hp5FaqAccordionContainer, HTMLStencilElement {
    }
    var HTMLHp5FaqAccordionContainerElement: {
        prototype: HTMLHp5FaqAccordionContainerElement;
        new (): HTMLHp5FaqAccordionContainerElement;
    };
    interface HTMLMyComponentAElement extends Components.MyComponentA, HTMLStencilElement {
    }
    var HTMLMyComponentAElement: {
        prototype: HTMLMyComponentAElement;
        new (): HTMLMyComponentAElement;
    };
    interface HTMLMyComponentBElement extends Components.MyComponentB, HTMLStencilElement {
    }
    var HTMLMyComponentBElement: {
        prototype: HTMLMyComponentBElement;
        new (): HTMLMyComponentBElement;
    };
    interface HTMLElementTagNameMap {
        "hp5-faq-accordion": HTMLHp5FaqAccordionElement;
        "hp5-faq-accordion-container": HTMLHp5FaqAccordionContainerElement;
        "my-component-a": HTMLMyComponentAElement;
        "my-component-b": HTMLMyComponentBElement;
    }
}
declare namespace LocalJSX {
    interface Hp5FaqAccordion {
    }
    interface Hp5FaqAccordionContainer {
    }
    interface MyComponentA {
    }
    interface MyComponentB {
    }
    interface IntrinsicElements {
        "hp5-faq-accordion": Hp5FaqAccordion;
        "hp5-faq-accordion-container": Hp5FaqAccordionContainer;
        "my-component-a": MyComponentA;
        "my-component-b": MyComponentB;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hp5-faq-accordion": LocalJSX.Hp5FaqAccordion & JSXBase.HTMLAttributes<HTMLHp5FaqAccordionElement>;
            "hp5-faq-accordion-container": LocalJSX.Hp5FaqAccordionContainer & JSXBase.HTMLAttributes<HTMLHp5FaqAccordionContainerElement>;
            "my-component-a": LocalJSX.MyComponentA & JSXBase.HTMLAttributes<HTMLMyComponentAElement>;
            "my-component-b": LocalJSX.MyComponentB & JSXBase.HTMLAttributes<HTMLMyComponentBElement>;
        }
    }
}
